export const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR';
export const FETCH_LIST_PENDING = 'FETCH_LIST_PENDING';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const TOGGLE_TODOLIST_ITEM = 'TOGGLE_TODOLIST_ITEM';
export const ADD_TODOLIST_ITEM = 'ADD_TODOLIST_ITEM';
export const DELETE_TODOLIST_ITEM = 'DELETE_TODOLIST_ITEM';